using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    [Header("移釉O定")]
    public float moveSpeed;
    public float jumpForce;          // 跳S力道
    public float jumpCooldown;       // O定要酌脶岵拍芟蛏咸S
    public float groundDrag;         // 地面的p速
    public float airMultiplier;      // 在空中的加乘速度，如果O定0就代表不能w，建h@值要小於1

    [Header("按I定")]
    public KeyCode jumpKey = KeyCode.Space;

    [Header("基本O定")]
    public Transform PlayerCamera;   // z影C

    [Header("地板_J")]
    public float playerHeight;       // O定玩家高度
    public LayerMask whatIsGround;   // O定哪一D邮巧渚可以打到的
    public bool grounded;            // 布林担河]有打到地面

    private bool readyToJump;        // O定是否可以跳S
    private float horizontalInput;   // 左右方向按I的抵(-1 <= X <= +1)
    private float verticalInput;     // 上下方向按I的抵(-1 <= Y <= +1)

    private Vector3 moveDirection;   // 移臃较

    private Rigidbody rbFirstPerson; // 第一人Q物件(z囊w)的w

    private void Start()
    {
        rbFirstPerson = GetComponent<Rigidbody>();
        rbFirstPerson.freezeRotation = true;         // i定第一人Q物件w旋D，不z囊w因榕龅轿锛就yD
        readyToJump = true;
    }

    private void Update()
    {
        MyInput();
        SpeedControl();   // y速度，^快就p速

        // 射出一l看不到的射，砼嘤]有打到地面？
        grounded = Physics.Raycast(transform.position, Vector3.down, playerHeight * 0.5f + 0.3f, whatIsGround);
        Debug.DrawRay(transform.position, new Vector3(0, -(playerHeight * 0.5f + 0.3f), 0), Color.red); // 在yA段⑸渚O定榧t色l，砜纯淳lL度虿颍
        // 如果碰到地板，就O定一反作用力(@可以u造人物移拥p速感)
        if (grounded)
            rbFirstPerson.drag = groundDrag;
        else
            rbFirstPerson.drag = 0;
    }

    private void FixedUpdate()
    {
        MovePlayer();     // 只要是物件移樱建h你放到FixedUpdate()        
    }

    // 方法：取得目前玩家按方向I上下左右的抵担控制跳S行
    private void MyInput()
    {
        horizontalInput = Input.GetAxisRaw("Horizontal");
        verticalInput = Input.GetAxisRaw("Vertical");

        // 如果按下O定的跳S按I
        if (Input.GetKey(jumpKey) && readyToJump && grounded)
        {
            readyToJump = false;
            Jump();
            Invoke(nameof(ResetJump), jumpCooldown); // 如果跳S^後，就依照O定的限制rg倒担rg到了才能往上跳S
        }
    }

    private void MovePlayer()
    {
        // 算移臃较(其就是算XScZS方向的力量)
        moveDirection = PlayerCamera.forward * verticalInput + PlayerCamera.right * horizontalInput;

        // 如果在地面，移臃绞槠胀ㄒ
        if (grounded)
        {
            moveDirection = new Vector3(moveDirection.x, 0, moveDirection.z);
            rbFirstPerson.AddForce(moveDirection.normalized * moveSpeed * 10f, ForceMode.Force);
        }
        // 如果不在地面，t移铀俣冗可以乘上一在空中的加乘底郑可以u造人物一跳往上w的超人w行效果
        else if (!grounded)
            rbFirstPerson.AddForce(moveDirection.normalized * moveSpeed * 10f * airMultiplier, ForceMode.Force);
    }

    // 方法：y速度Kp速
    private void SpeedControl()
    {
        Vector3 flatVel = new Vector3(rbFirstPerson.velocity.x, 0f, rbFirstPerson.velocity.z); // 取得HXScZS的平面速度

        // 如果平面速度大於AO速度值，就⑽锛的速度限定於AO速度值
        if (flatVel.magnitude > moveSpeed)
        {
            Vector3 limitedVel = flatVel.normalized * moveSpeed;
            rbFirstPerson.velocity = new Vector3(limitedVel.x, rbFirstPerson.velocity.y, limitedVel.z);
        }
    }

    // 方法：跳S
    private void Jump()
    {
        // 重新O定YS速度
        rbFirstPerson.velocity = new Vector3(rbFirstPerson.velocity.x, 0f, rbFirstPerson.velocity.z);
        // 由下往上推第一人Q物件，ForceMode.Impulse可以推送的模式橐凰查g，更像跳S的感X
        rbFirstPerson.AddForce(transform.up * jumpForce, ForceMode.Impulse);
    }

    // 方法：重新O定readyToJumptrue的方法
    private void ResetJump()
    {
        readyToJump = true;
    }
}
